swagger: '2.0'
info:
  title: Copy-and-Paste
  version: "0.0.1"
schemes:
  - https
  - http
securityDefinitions:
  bearer:
    type: apiKey
    name: Authorization
    in: header
basePath: /api
produces:
  - application/json
paths:
  /connect/{id}:
    x-swagger-router-controller: connect
    post:
      operationId: connectById
      summary: Connects to client specified by ID
      description: |
        This function will reserve the client with specified ID to you. No other client can communicate with this client anymore
      tags:
        - connect
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        200:
          description: Succesfully connected
          schema:
            type: object
            required:
              - msg
              - token
            properties:
              msg: 
                type: string
              token: 
                type: string
                description: Bearer token that can be used to send data to web-client
        404:
          description: ID is not found
          schema:
            $ref: '#/definitions/Error'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Internal server error occured
          schema:
            $ref: '#/definitions/Error'
  /send:
    x-swagger-router-controller: send
    post:
      operationId: sendById
      summary: Sends information to web-client
      description: With this method you can send data directly to web-client. You have to use /connect API call first to get bearer token.
      tags:
        - send
      security:
        - bearer: []
      parameters:
        - name: body
          in: body
          description: Message body
          schema:
            $ref: '#/definitions/PostData'
          required: true
      responses:
        200:
          description: The data has been succesfully send and received by the web-client
          schema:
            $ref: '#/definitions/Success'
        400:
          description: The message in body is missing
          schema:
            $ref: '#/definitions/Error'
        404:
          description: ID is not found
          schema:
            $ref: '#/definitions/Error'
        408:
          description: Web-client did not response to this message in specified time. You may try to send message again
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Internal server error occured
          schema:
            $ref: '#/definitions/Error'
definitions:
  PostData:
    type: object
    required:
      - data
    properties:
      data: 
        type: string
  Success:
    type: object
    properties:
      msg:
        type: string
  Error:
    type: object
    properties:
      msg:
        type: string